### PR TITLE
Provide to loggers 'remoteAddress' key via MDC.

### PR DESCRIPTION
**Pull request by ckovorodkin**
MDCWrapper is used to wrap invocations via custom MDC keys.

### CODE REVIEW

**Comment by atomashpolskiy** [comment]
This complicates code quite a bit.. What value does it bring to the table?

**Comment by ckovorodkin** [comment]
The main goal is to log peers remote address to simplify connection tracking.
Pay attention to value `/11.22.33.44:55555` in example below:
```
2018-02-12 08:39:56.514 ERROR  /11.22.33.44:55555 | [bt.net.data-receiver] DataReceivingLoop:141 - Failed to process key
java.lang.RuntimeException: Unexpected I/O error
	at bt.net.pipeline.SocketChannelHandler.read(SocketChannelHandler.java:83)
	at bt.net.pipeline.DefaultChannelPipeline$DefaultChannelHandlerContext.fireChannelReady(DefaultChannelPipeline.java:192)
	at bt.net.DataReceivingLoop.processKey(DataReceivingLoop.java:180)
	at bt.net.DataReceivingLoop.lambda$run$4(DataReceivingLoop.java:134)
	at bt.logging.MDCWrapper.run(MDCWrapper.java:44)
	at bt.net.DataReceivingLoop.run(DataReceivingLoop.java:130)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
	at bt.net.pipeline.SocketChannelHandler.processInboundData(SocketChannelHandler.java:137)
	at bt.net.pipeline.SocketChannelHandler.read(SocketChannelHandler.java:80)
	... 8 more
```

**Comment by atomashpolskiy** [comment]
Yeah, but why do it with MDC, which is infamous for being very tricky to use correctly in a multi-threaded environment without introducing subtle bugs? The same effect is currently achieved by directly adding peer or socket address to the log message in a way that is clear and straight-forward. In contrast, you're over-complicating things that ought to be simple and introduce yet another thing to remember of.

**Comment by ckovorodkin** [comment]
Unfortunately, I have to disagree. I have a positive experience using this method of logging. It simplifies the construction of messages for the log. And also, not all locations in code have access to the remote address. And not all code that logs messages should care about remote address.

**Pull request closed without merging**
