### PR TITLE
Don't query tracker too frequently.

### PR DESCRIPTION
**Pull request by ckovorodkin**

### CODE REVIEW

**Comment by atomashpolskiy** [comment]
The problem with this is that many trackers return inadequately large interval values (more than 24 hours in some cases), so it makes more sense to have a configuration option to control the periodicity of querying with a reasonable default value. I don't think that once in 5 minutes is perceived as "frequently" in 2018.

As for the frequency of DHT and other peer lookups, this is supposed to be configured [here](https://github.com/atomashpolskiy/bt/blob/master/bt-core/src/main/java/bt/runtime/Config.java#L68) and setup [here](https://github.com/atomashpolskiy/bt/blob/master/bt-core/src/main/java/bt/peer/PeerRegistry.java#L99-L100). Note that some peer sources (like DHT) extend `bt.peer.ScheduledPeerSource`, which does not allow to perform a new lookup until the previous one has finished. I.e. the interval between lookups is determined by lookup duration and is no less than `Config#peerDiscoveryInterval`.

**Comment by ckovorodkin** [comment]
> The problem with this is that many trackers return inadequately large interval values (more than 24 hours in some cases), so it makes more sense to have a configuration option to control the periodicity of querying with a reasonable default value. I don't think that once in 5 minutes is perceived as "frequently" in 2018.

My problem with this is that my favourite tracker uses interval of about 50 minutes and I don't want to get penalty by querying it too frequently :)

I think that the default implementation should correctly use the preferred interval. And the ability to limit too long an interval can be provided additionally, disabled by default.

> As for the frequency of DHT and other peer lookups...

In the current implementation, a nonstop DHT lookup is obtained. This is wasteful for multi-torrent environment. 

By the way, it will be better if the `ScheduledPeerSource` will support the search interval itself. And `PeerRegistry` acts as a handler for discovered peers instead of the periodic request `ScheduledPeerSource`.

**Comment by atomashpolskiy** [comment]
> My problem with this is that my favourite tracker uses interval of about 50 minutes and I don't want to get penalty by querying it too frequently :)

You may set config's `trackerQueryInterval` to 50 minutes.

> I think that the default implementation should correctly use the preferred interval.

I happen to think differently. rutracker.org uses interval of a few days, and I really don't see that as a sane default

> In the current implementation, a nonstop DHT lookup is obtained. This is wasteful for multi-torrent environment.

Yep, the next lookup starts executing as soon as the previous one has finished. Currently `DHTPeerSourceFactory` uses a cached thread-pool executor for creating torrent peer sources, which means that there will be one thread per torrent, which indeed is wasteful.

One possible solution would require two changes:
- use executor with a fixed number of threads
- collect peers for the torrent (i.e. query peer sources) only if the number of peers for this torrent is insufficient

The specific way of determining if the number of peers for some torrent is insufficient is a subject for discussion in a new ticket.

**Comment by ckovorodkin** [comment]
> I happen to think differently. rutracker.org uses interval of a few days, and I really don't see that as a sane default

Just checked. For me it returns 3412 sec, that is 56 minutes and 52 seconds.

**Comment by atomashpolskiy** [comment]
3022 for me. Maybe rutracker has been updated, or it was some other tracker. Anyways, we don't want to depend on the values provided by some arbitrary tracker implementation/configuration.

**Comment by ckovorodkin** [comment]
> Anyways, we don't want to depend on the values provided by some arbitrary tracker implementation/configuration.

Why not? Some trackers can be fast, some of them can be slow. If the tracker updates its own lists once a day/hour/minute and tells about it in response, then it makes no sense to querry it more often.

**Comment by atomashpolskiy** [comment]
It makes sense in more mature client implementations, that persist collected peers and re-use them when necessary, so they don't need to query the tracker. It does not make sense in Bt at current moment of time, because we don't use the the peer cache yet. First things first.

**Comment by ckovorodkin** [comment]
Well, I will send these updates in a larger pull request, if any.

**Pull request closed without merging**
