### PR TITLE
Implemented PiecesBar for CLI

### PR DESCRIPTION
**Pull request by ckovorodkin**
Also, added method TorrentSessionState.getPieces() that returns BitSet of pieces, that status is PieceStatus.COMPLETE_VERIFIED.

### CODE REVIEW

**Comment by atomashpolskiy** [comment]
Printing a "histogram" of completed pieces in CLI is an awesome idea, I really like it. Just two comments:
- default impl of getPieces() does not make much sense, because we usually care about the position of a piece; also I generally tend to dislike default methods unless it's a functional interface or added temporarily for backwards compatibility reasons
- I'm not quite sure, but is it necessary to reverse bits? E.g. in the Bitfied class itself we occasionally use BitSet and create it from the 'value' bitmask directly: https://github.com/atomashpolskiy/bt/blob/master/bt-core/src/main/java/bt/data/Bitfield.java#L125

**Comment by atomashpolskiy** [comment]
Oh, and let's have a dedicated instance of BitSet instead of creating a new one on each call

**Comment by ckovorodkin** [comment]
> I'm not quite sure, but is it necessary to reverse bits? E.g. in the Bitfied class itself we occasionally use BitSet and create it from the 'value' bitmask directly: https://github.com/atomashpolskiy/bt/blob/master/bt-core/src/main/java/bt/data/Bitfield.java#L125

Seams like bug in Bitfield.java#L125. The high bit in the first 'value' byte corresponds to piece index 0, while BitSet takes first bit from low bit in the first byte.
Take a look at that code:
https://github.com/atomashpolskiy/bt/blob/a37ca29f3585d0b34a2fbeb532a92368432dae9c/bt-core/src/main/java/bt/data/Bitfield.java#L240
https://github.com/atomashpolskiy/bt/blob/a37ca29f3585d0b34a2fbeb532a92368432dae9c/bt-core/src/main/java/bt/protocol/Protocols.java#L214

**Comment by atomashpolskiy** [comment]
Yeah, actually it's not a bug :) It reflects the requirement of the BitTorrent messaging protocol that the bitfield is encoded in "little-endian" format with regards to _bits_ (i.e. piece №0 is represented by the _highest_ bit in the first byte). It does not matter in Bitfield.java#L125, because we need only cardinality. But since the order of bits actually matters in many cases, it's a good idea to make this information explicit, in a similar fashion to how it's done in BitSet by using a `ByteOrder` enum. Then, methods in `Bitfield` that accept or return a `byte[]` bitmask, will have an additional parameter `byteOrder`. 

I.e. we'll add:
- new constructor `bt.data.Bitfield#Bitfield(byte[], int, java.nio.ByteOrder)`
- overloaded method `bt.data.Bitfield#getBitmask(ByteOrder)`

Internally we'll perform normalization and store bitmasks in one particular format, maybe the one that is compatible with `BitSet`.

What do you think?

**Comment by ckovorodkin** [comment]
> Yeah, actually it's not a bug :) ... It does not matter in Bitfield.java#L125, because we need only cardinality.

Yes, you are right :) It is just a trick.

I think, that "reverse bit order" is related only to BitTorrent Protocol Message Layer. And outside that layer should be used native bit order, i. e. bit order, that is compatible with java.util.BitSet.
"Reverse bit order" is used in only one point:
https://github.com/atomashpolskiy/bt/blob/a37ca29f3585d0b34a2fbeb532a92368432dae9c/bt-core/src/main/java/bt/net/BitfieldConnectionHandler.java#L51
But may be for speed optimisation it will be better to track byte[] with "reverce bit order' by Bitfield.java in addition to BitSet for rest of BT code. But that byte[] variable will be used in only that instance of Bitfield, that represent availability of local blocks, not remote peer. That role of Bitfield may be clarified by passing boolean parameter to Bitfield constructor.

**Comment by ckovorodkin** [comment]
> default impl of getPieces() does not make much sense, because we usually care about the position of a piece; also I generally tend to dislike default methods unless it's a functional interface or added temporarily for backwards compatibility reasons

Default implementation of getPieces() was added "temporarily for backwards compatibility reasons".
It can be removed as soon as migration timeout expired.

**Comment by atomashpolskiy** [comment]
@ckovorodkin , I'm not sure if you have read my comment :) If you have difficulty communicating in English, we can switch to Russian. Basically, I've provided a high-level description of what needs to be done in the comment that you were responding to. Feel free to ask any question!

> Default implementation of getPieces() was added "temporarily for backwards compatibility reasons".

But it's a new method, isn't it? What exactly needs to be backward compatible here?

**Comment by ckovorodkin** [comment]
> Oh, and let's have a dedicated instance of an empty BitSet instead of creating a new one on each call. In fact we could probably have a single instance that would be updated when getPieces() is called

A BitSet is not safe for multithreaded use without external synchronization. So I can't see how we can avoid of new instance creation per each call of getPieces().

If BitSet field will be implemented in Bitfield, than it will be effective to use clone() in Bitfield method asBitSet().

**Comment by atomashpolskiy** [comment]
> A BitSet is not safe for multithreaded use without external synchronization. So I can't see how we can avoid of new instance creation per each call of getPieces().

TorrentSessionState instance is not supposed to be shared between multiple threads, so it's not a problem.

> If BitSet field will be implemented in Bitfield

I think this field should be in the DefaultTorrentSessionState class.

**Comment by ckovorodkin** [comment]
> But it's a new method, isn't it? What exactly needs to be backward compatible here?

If some one already implemented its own version of TorrentSessionState, than introducing new getPieces() without default implementation makes his library incompatible with new version of BT.

I don't need that default implementation of getPieces()  and can remove it at any time )

**Comment by ckovorodkin** [comment]
> TorrentSessionState instance is not supposed to be shared between multiple threads, so it's not a problem.

But DefaultTorrentSessionState uses synchronized methods and AtomicLong. That is misleading.
Shold be removed synchronized methods and AtomicLong from DefaultTorrentSessionState ?

**Comment by atomashpolskiy** [comment]
> If some one already implemented its own version of TorrentSessionState, than introducing new getPieces() without default implementation makes his library incompatible with new version of BT.

Oh, I see. I think this is a bit far-fetched. This kind of incompatibility is expected when upgrading to a new version, and the user is obliged to implement the new method, since it was his decision to implement an interface (as opposed to extending the default implementation).

> I don't need that default implementation of getPieces() and can remove it at any time

Yeah, I think we're better off without it. Thanks!

> But DefaultTorrentSessionState uses synchronized methods and AtomicLong. That is misleading.
Shold be removed synchronized methods and AtomicLong from DefaultTorrentSessionState ?

No, these should not be removed, as they are used to synchronize the Bt thread and the user thread. 
In our case we don't care about the Bt thread, because the new `getPieces()` method is going to be called from the user thread only. So it's safe to have a private field that will be updated and read in `getPieces()` method only.

**Comment by atomashpolskiy** [comment]
It seems error-prone to manage two equivalent bitmask representations in parallel. Can we restrict the usage of BitSet by the DefaultTorrentSessionState class only?

`getPieces()` can probably be simplified to return the result of `descriptor.getDataDescriptor().getBitfield().getBitSet()`, when it's present, or a special empty BitSet instance otherwise

> How about moving bt.data.Bitfield#reverseBitOrder(byte[]) to bt.protocol.Protocols ?

I agree

**Comment by ckovorodkin** [comment]
> It seems error-prone to manage two equivalent bitmask representations in parallel.

Seams like that behaviour can speed up calculations in Bitfield. I afraid, that repeatedly invocations of getBitmask() or getBitSet() is quite heavy operations.

> Can we restrict the usage of BitSet by the DefaultTorrentSessionState class only?

I have some plans that utilizes this BitSet in new logic.

**Comment by atomashpolskiy** [comment]
> Seams like that behaviour can speed up calculations in Bitfield. I afraid, that repeatedly invocations of getBitmask() or getBitSet() is quite heavy operations.

Well, maybe the BitSet is not the right thing to use here then? I.e. it adds unnecessary complexity (performance considerations, maintenance burden) without providing much value. I'd also argue that the `java.util.BitSet` interface is not the best thing to have in a public-facing API like session state. It has many not needed methods and methods that don't make sense in the context of pieces, and also methods that essentially duplicate the existing functionality like `BitSet#size()` (same as `TorrentSessionState#getPiecesTotal()`).

So, let's rather add a `TorrentSessionState#isPiecePresent(int)` method that internally will use the existing `Bitfield#isVerified(int)`. This will greatly simplify things and won't require any internal changes.

**Pull request closed without merging**
