### PR TITLE
Avoid logging of potentially sensitive query in HttpTracker.

### PR DESCRIPTION
**Pull request by ckovorodkin**
In come cases that query contains users private key. For security reasons private key mast be excluded from logs.
Same work need to be done for UDP tracker.

### CODE REVIEW

**Comment by atomashpolskiy** [comment]
Do you plan to update UDP handler in this or a different PR? I.e. should I merge or wait? :) thanks!

**Comment by ckovorodkin** [comment]
Implemented for UdpTracker

**Comment by atomashpolskiy** [comment]
Thanks! May I ask you to do two more things:
1) Please remove `@author` annotations and `final` modifiers for local variables
2) The test itself is fine, but there seems to be a problem with how a UdpTracker is constructed in the library. Right now it creates a "worker" instance internally, which means that in the unit test we need to provide it with some services that don't make much sense in that context. As a result, we have to write extra code, and the tests run slower and do more things than is really necessary. What would you say, if I suggest passing `UdpMessageWorker` instance into `UdpTracker` constructor? The logic of assembling worker and tracker would then be moved to `UdpTrackerFactory` class, and in the test we won't need to create any mocks (which I tend to **strongly** dislike).

**Comment by ckovorodkin** [comment]
Same work need to be done for `bt.tracker.AnnounceKey#toString`.

**Comment by atomashpolskiy** [comment]
I wonder if we can mask only the secret key value and not the whole query?

**Pull request closed without merging**
