### PR TITLE
Randomized rarest-first selector bugfix

### PR DESCRIPTION
**Pull request by ckovorodkin**

### CODE REVIEW

**Comment by atomashpolskiy** [comment]
Hi, thanks for the PR! There are some issues with it though

1) Which malfunction is 72f4be8 supposed to fixed?
2) I'd prefer to keep the original `shuffle`, because `ArrayList#subList` returns a very "defensive" type of list, that performs additional checks upon each method invocation. Piece selection is one of the "hotter" places in code and may be called very often in certain situations, so we'd like to keep the number of created objects and needless ops to a minimum
3) `bt.torrent.selector.RarestFirstSelector` is a very nice visualization indeed, and it helped me to quickly understand the core issue. However, it's not an auto test, so it would be better fitted in _examples_ submodule with a short, descriptive readme doc.

3d889eb is fine, good catch, though we might simplify it even further:
```java
while (limit < list.size() && getCount(list.get(limit++)) == count)
    ;
```
But it's a matter of taste, so feel free to leave it as it is. I personally tend to like C-style "body-less" loops more.

**Comment by ckovorodkin** [comment]
Attached files contains visualisation of malfunction that was fixed in [72f4be8](https://github.com/atomashpolskiy/bt/commit/72f4be860a2371435e620de951e9a71ef882d28f):
[RarestFirstSelector-randomizedRarest-expected.txt](https://github.com/atomashpolskiy/bt/files/1696563/RarestFirstSelector-randomizedRarest-expected.txt)
[RarestFirstSelector-randomizedRarest-actual-malfunction.txt](https://github.com/atomashpolskiy/bt/files/1696565/RarestFirstSelector-randomizedRarest-actual-malfunction.txt)

**Comment by ckovorodkin** [comment]
About [3d889eb](https://github.com/atomashpolskiy/bt/commit/3d889eb7f2554e72bdf3da0597053409beb69c11):
No, if you move increment of 'limit' from body to condition than you count extra item witch have different count.

**Comment by ckovorodkin** [comment]
> I'd prefer to keep the original shuffle, because ArrayList#subList returns a very "defensive" type of list, that performs additional checks upon each method invocation. Piece selection is one of the "hotter" places in code and may be called very often in certain situations, so we'd like to keep the number of created objects and needless ops to a minimum

Ok. Commit was removed.

**Comment by ckovorodkin** [comment]
> `bt.torrent.selector.RarestFirstSelector` is a very nice visualization indeed, and it helped me to quickly understand the core issue. However, it's not an auto test, so it would be better fitted in _examples_ submodule with a short, descriptive readme doc.

[7f9643d](https://github.com/ckovorodkin/bt/commit/7f9643de20a12bcfc6ac8c7327e9bcc818207ad2) ExaminePieceSelector moved to submodule 'examples'.

**Comment by atomashpolskiy** [comment]
> About 3d889eb:
No, if you move increment of limit from body to condition than you count extra item witch have different count.

Right. Damn :)

> Attached files contains visualisation of malfunction that was fixed in 72f4be8

It was kind of expected... The idea is that we always choose no less than `SELECTION_MIN_SIZE` pieces  to reduce the number of times that the next pieces are re-calculated (the worst case in this regard would be that all pieces had different availability), but yeah, one unfortunate consequence of this approach is that when the number of pieces that share the same availability (`BULK_SIZE` in your case) is less than `SELECTION_MIN_SIZE`, then the trailing pieces in the selected subset are yielded strictly in the order of increasing availability. Though, it should be noted that:
* it has no effect on the download when `SELECTION_MIN_SIZE - BULK_SIZE` is less than or equal to the number of peers who have the selected pieces
* in most cases the order of increasing availability would not be the same as the natural order of the piece indices (i.e. randomized-rarest does not become a sequential download, it just deteriorates to strictly-rarest)

So, this boils down to a tradeoff between:
- either being strictly randomized-rarest in all cases,
- or allowing sequential-rarest behavior for a small number of pieces but cutting down the number of recalculations by a factor of `SELECTION_MIN_SIZE` for the worst case

`calculateLimitAndShuffle` is not very expensive though, so this might very well be a premature optimization...

**Comment by atomashpolskiy** [comment]
In fact the best decision could be to leave `SELECTION_MIN_SIZE` logic but shuffle all pieces in the selection (separately for each group of pieces that share the same availability, of course, to prevent pushing less available pieces to the bottom of the queue)

**Comment by ckovorodkin** [comment]
How about moving shuffle operation into `RandomizedIteratorOfInt.nextInt()`? That will result in only one `random.nextInt()` invocation per `nextInt()` without (potentially rejected) precalculations for further invocations.

**Pull request closed without merging**
