### PR TITLE
resource clean and other change

### PR DESCRIPTION
**Pull request by a8156268**
based on two ideas:   
1. when torrent/BtClient is stopped, all resource about that torrent should be cleaned.
2. when BtRuntime shutdown, all resource about Bt should be cleaned.

### CODE REVIEW

**Comment by a8156268** [comment]
shall this pull request been merged？

**Comment by atomashpolskiy** [comment]
Hi! Sorry, very busy lately, but will try to look into it shortly!

**Comment by a8156268** [comment]
Thanks for approving.

**Comment by atomashpolskiy** [comment]
You are welcome! I truly appreciate your effort and patience.

**Pull request merged**
